### Get Root
GET http://localhost:3000

### Get Products
GET http://localhost:3000/products/

### Post Products
POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "Book 1",
    "desc": "Book about science"
}